artistProfile: 'Perfil do Artista',
loadingArtist: 'A carregar artista...',
artistNotFound: 'Artista não encontrado',
backToArtists: 'Voltar aos artistas',
following: 'A seguir',
follow: 'Seguir',
supportArtist: 'Apoiar Artista',
messageArtist: 'Falar com artista',
videos: 'Vídeos',
videosLower: 'vídeos',
songs: 'Músicas',
artistNoVideos: 'Este artista ainda não tem vídeos.',
artistNoSongs: 'Este artista ainda não tem músicas.',
useMusicLive: 'Usar esta música na live',
releases: 'lançamentos',
plays: 'plays',
likes: 'likes',
followers: 'seguidores',
coinPerMessage: 'coin por mensagem',
liveArtistFallback: 'Artista Live',
temporaryLiveProfile: 'Perfil temporário criado a partir da live.',
licenseNotDefined: 'Esta música ainda não tem licença definida pelo artista.',
licenseBought: 'Licença comprada por €{{price}}. Já pode usar esta música em live.',